# Generated by Django 4.0.2 on 2022-03-07 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='facture',
            name='ref_fac',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('P', 'Payée'), ('N', 'Non-Payée'), ('A', 'Avance Donnée')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='total',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='tva',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.facture')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('adress', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.facture')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('adress', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.facture')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
