# Generated by Django 4.0.2 on 2022-03-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0003_remove_client_facture_remove_fournisseur_facture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='tva',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='price',
        ),
        migrations.AddField(
            model_name='produit',
            name='price_ht',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='tva',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
