# Generated by Django 4.0.2 on 2022-03-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_remove_facture_tva_remove_produit_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='price_ht',
            new_name='prix_u_ht',
        ),
        migrations.AddField(
            model_name='produit',
            name='montant',
            field=models.IntegerField(null=True),
        ),
    ]
