# Generated by Django 4.0.2 on 2022-03-18 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0005_rename_price_ht_produit_prix_u_ht_produit_montant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AddField(
            model_name='client',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produit',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
