# Generated by Django 4.0.2 on 2022-03-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0007_alter_client_options_alter_facture_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='facture',
        ),
        migrations.AddField(
            model_name='produit',
            name='facture',
            field=models.ManyToManyField(to='facture.Facture'),
        ),
    ]
