# Generated by Django 4.0.2 on 2022-03-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0008_remove_produit_facture_produit_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='facture',
        ),
    ]
