# Generated by Django 4.0.2 on 2022-03-23 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facture', '0009_remove_produit_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='facture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facture.facture'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
