# Generated by Django 4.0.2 on 2022-03-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0010_produit_facture_alter_produit_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='facture',
        ),
        migrations.AddField(
            model_name='produit',
            name='facture',
            field=models.ManyToManyField(to='facture.Facture'),
        ),
    ]
