# Generated by Django 4.0.2 on 2022-03-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0011_remove_produit_facture_produit_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
