# Generated by Django 4.0.2 on 2022-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0012_alter_facture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
