# Generated by Django 4.0.2 on 2022-03-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0013_alter_facture_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={},
        ),
    ]
