# Generated by Django 4.0.2 on 2022-03-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0014_alter_produit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-pk']},
        ),
    ]
