# Generated by Django 4.0.2 on 2022-05-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0015_alter_produit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('P', 'Payée'), ('N', 'Non-Payée'), ('A', 'Avance Donnée')], default='P', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='montant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_u_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='qty',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
