# Generated by Django 4.0.2 on 2022-06-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0016_alter_facture_status_alter_produit_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('P', 'Payée'), ('N', 'Non-Payée'), ('A', 'Avance Donnée')], default='P', max_length=255, null=True),
        ),
    ]
